#! /bin/bash
#	wordsel M N
# read stdin and print words M-N inclusive.

M=$1; shift
N=$1; shift
((d=N-M+1))
if ((d < 0)); then
	d=0
fi

while read -r line; do
	declare -a words=($line)
	echo "${words[@]:$M:$d}"
done
